---
### container
container_log_driver: journald

### common
aap_volumes_dir: '{{ ansible_user_dir }}/aap'
archive_compressed_extension: "tar.gz"
archive_decompressed_extension: "tar"

### backup/restore
pcp_use_archive_compression: "{{ use_archive_compression | default(true) }}"

### pcp
pcp_conf_dir: "{{ aap_volumes_dir }}/pcp/etc"
pcp_pmcd_port: 44321
pcp_pmproxy_port: 44322
pcp_protocol: tcp
pcp_firewall_zone: public
...
